---
platform: linux
image: docker:///concourse/static-golang

inputs:
  - name: tracker-git-branch-resource
    path: gopath/src/github.com/adamstegman/tracker-git-branch-resource

run:
  path: gopath/src/github.com/adamstegman/tracker-git-branch-resource/scripts/test
